# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "Desktop App Template"
description = "A C++ template for building cross-platform desktop apps with ImGui and OpenGL"
languages = ["C", "CXX"]
apple.languages = ["OBJC"]
cmake-after = """
if(WIN32)
  set(SPDLOG_WCHAR_FILENAMES ON)
endif()
"""

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true
BUILD_GMOCK = false
CURL_USE_LIBPSL = false
BUILD_EXAMPLES = false
BUILD_LIBCURL_DOCS = false
BUILD_MISC_DOCS = false
BUILD_CURL_EXE = false

# dependencies
[fetch-content.glfw]
git = "https://github.com/glfw/glfw"
tag = "3.5.1"
[fetch-content.nlohmann_json]
git = "https://github.com/nlohmann/json"
tag = "v3.12.0"
[fetch-content.imgui]
git = "https://github.com/ocornut/imgui"
tag = "v1.92.9b"
[fetch-content.spdlog]
git = "https://github.com/gabime/spdlog"
tag = "v1.17.0"
[fetch-content.gtest]
git = "https://github.com/google/googletest"
tag = "v1.18.0"
[fetch-content.nfd]
git = "https://github.com/btzy/nativefiledialog-extended"
tag = "v1.3.0"
[fetch-content.curl]
git = "https://github.com/curl/curl"
tag = "curl-8_21_0"

# targets
[target.imgui]
type = "static"
sources = [
    "${imgui_SOURCE_DIR}/imgui.cpp",
    "${imgui_SOURCE_DIR}/imgui_draw.cpp",
    "${imgui_SOURCE_DIR}/imgui_tables.cpp",
    "${imgui_SOURCE_DIR}/imgui_widgets.cpp",
    "${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp",
    "${imgui_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp"
]
link-libraries = ["glfw"]
include-directories = ["${imgui_SOURCE_DIR}", "${imgui_SOURCE_DIR}/backends"]
compile-features = ["cxx_std_23"]

[target.template_lib]
type = "static"
sources = ["lib/src/**.cpp", "lib/include/**.hpp"]
include-directories = ["lib/include"]
compile-features = ["cxx_std_23"]
link-libraries = ["nlohmann_json::nlohmann_json", "spdlog::spdlog", "CURL::libcurl"]
precompile-headers = ["lib/include/lib_pch.hpp"]

[target.template_app]
type = "executable"
sources = [
    "gui/**.cpp",
    "gui/**.hpp",
    "vendor/imgui/imgui_stdlib.cpp",
    "vendor/glad/**.c",
]
include-directories = [
    "gui",
    "vendor/imgui",
    "vendor/glad/include",
    "vendor/stb"
]
compile-features = ["cxx_std_23"]
link-libraries = ["template_lib", "imgui", "spdlog::spdlog", "nfd"]
precompile-headers = ["gui/pch.hpp"]
cmake-after = """
if(WIN32)
  set(CURL_USE_SCHANNEL ON)
endif()
"""

[target.template_app.windows]
link-libraries = ["Dwmapi"]

# helper that does one operation with elevated permissions
[target.template_elevationhelper]
type = "executable"
sources = [
    "elevation/**.cpp",
    "elevation/**.hpp",
]
include-directories = [
    "elevation",
]
compile-features = ["cxx_std_23"]
link-libraries = ["spdlog::spdlog", "template_lib"]
precompile-headers = ["lib/include/lib_pch.hpp"]

# tests
[target.template_tests]
type = "executable"
sources = ["tests/**.cpp"]
include-directories = ["lib/include"]
compile-features = ["cxx_std_23"]
link-libraries = ["GTest::gtest_main", "template_lib"]
precompile-headers = ["lib/include/lib_pch.hpp"]
cmake-after = """
enable_testing()
add_test(NAME template_tests COMMAND template_tests)
"""
